### PR TITLE
Add ReleaseNotesURL

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Add ReleaseNotesURL for next Marketplace release. The version number as to be bumped when the next release is cut.

### CODE REVIEW

**Comment by larkox** [comment]
@jfrerich Would you mind update your gitbook on release process to keep in track this change?

**Comment by jfrerich** [comment]
@larkox Done.

https://app.gitbook.com/@jason-frerich/s/plugin-release-process/#bump-current-version-of-an-existing-plugin

I feel like we should somehow automate this task with `make apply`?  @hanzei what do you think?

**Comment by jfrerich** [comment]
Also, what do you guys think about moving the gitbook docs into the developer docs?

**Comment by hanzei** [comment]
> @larkox Done.

Thanks :+1: 

> [app.gitbook.com/@jason-frerich/s/plugin-release-process/#bump-current-version-of-an-existing-plugin](https://app.gitbook.com/@jason-frerich/s/plugin-release-process/#bump-current-version-of-an-existing-plugin)
> 
> I feel like we should somehow automate this task with `make apply`? @hanzei what do you think?

That is a great idea :+1: I've been tinkering out with `make apply` and will add that idea to my progress.

> @hanzei will you be cutting the release again for v0.3.0 so that this is included?

No, not having a release notes URL is not a big deal.

> Also, what do you guys think about moving the gitbook docs into the developer docs?

:+1: This is also on my list as consolidating the Integrations team docs.

**Pull request merged**
