### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by larkox**
### Summary
Bump version to v0.3.0

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* 6b53adb Add todo button on team sidebar (#54)
* 2c70ff0 Add autocomplete (#69)

#### Fixes
* 3ced534 Added missing commands to autocomplete suggestion (#65)
* 954f18e Add Homepage and Support URL (#57)
* fb37af3 Use bot account to post slash command responses (#52)
* 204ec2a Normalize plugin name (#79)
* 889ce94 Allow extra spaces between commands (#86)
* bcb8a56 Render markdown on custom post types (#85)
* 9f95dfa Move registerReducer call to the top of `initialize` (#60)

#### Others
* 7d33ee9 [GH-58] GolangCI-Lint integration (#63)
* 986185d add badges for HW and latest release (#68)
* f9e41c1 Drop second maintainer from CODEOWNERS (#55)
* d90daeb v0.3.0 Upgrade dependencies and go mod tidy (#74)
* 4adaec7 v0.3.0 Audit fix (#73)
* 61bf98c Add .npmrc file for save-exact packages (#80)

### Ticket Link
None

### CODE REVIEW

**Comment by larkox** [comment]
We have pending these two PRs, but since we might be adding a new version soon, we can squish them in the next bump.
#73 Audit fix
#74 Go mod tidy

**Comment by hanzei** [comment]
Maybe https://github.com/mattermost/mattermost-plugin-todo/pull/69 should also go into this release as it's an awesome UX improvement.

**Comment by larkox** [comment]
@hanzei If it is merged before the release, we will squish it. If not, as soon as it is merged we will prepare a new bump.

**Comment by larkox** [comment]
Added three commits to the changelog on an `others` section. Mainly commits that are not fixes nor enhancements, but more related with repo maintenance. Not sure whether these should be added here, not added at all, or what to do with them.

**Comment by DHaussermann** [comment]
Sorry for the delay on this @larkox the PRs listed can be merged so we can release test now for the version bump..

**Comment by hanzei** [comment]
@DHaussermann This is ready for a final review.

**Comment by larkox** [comment]
Updated comment with all new commits merged.

**Comment by DHaussermann** [comment]
Release testing was completed. There are a couple issues found:
1. https://github.com/mattermost/mattermost-plugin-todo/issues/83 is an edge case but it is a new regression and crashes the plugin. (may need help from @iomodo 
2. https://github.com/mattermost/mattermost-plugin-todo/issues/84 is relatively minor and not a regression.

cc @larkox

**Comment by larkox** [comment]
@DHaussermann All pending issues have been merged and the description has been updated with the latest commits.

**Comment by larkox** [comment]
We might be waiting for #90 .
Personally, I have no problem in releasing v0.3.0 as it is, and bumping a new release when that is in place, but since the main overhead will be on QA side, I will defer this decision to @DHaussermann

**Comment by DHaussermann** [comment]
@aaronrothschild I can run through release tests if we want to ship this. My impression was that we were going to follow-up on if it's acceptable to deploy this as is or if we want a flag to hide the team side bar UI options.
Thoughts?

**Comment by DHaussermann** [comment]
#90 moved to v0.4.0 after team discussion.

**Pull request merged**
