### PR TITLE
Fix websocket reconnect

### LINKED ISSUE #155: Various plugin on Community throw JS errors after upgrading to version 0.5.0
After upgrading the community server to version `v0.5.0` of the ToDo plugin, many users reported seeing multiple JS errors from various plugins. 
The errors seem to mostly show `[Util] handleerror:: Uncaught TypeError: Cannot read property of undefined (reading 'data')`
image
image

These error then stopped occurring once the plugin was downgraded again to `v0.4.0`. 

I have not yet found local reproduction steps for this set of errors but, this must be investigated and resolved.

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix websocket reconnect, which was flooding the console with errors that were attributed to other plugins.

#### Notes for testing
To force a websocket reconnect, you can disconnect from the network (you will see after a short while a message in the console stating that the websocket connection was closed), and connect again.

In the published version this will trigger the error flood, while the new version should work without any problem.

The piece of functionality (and that probably should be tested too) that used this event is both the list on the RHS and the counters on the LHS. In order to test this, go offline (i.e. websocket connection closed), in a different client create a todo and then reconnect. The new todo should appear in the RHS and in the counters on the LHS.

#### Ticket Link
Fix #155

### CODE REVIEW

**Comment by hanzei** [comment]
@sanjaydemansol please take a look

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@sanjaydemansol Gentle reminder to review this PR

**Comment by hanzei** [comment]
@dipak-demansol Could you please review this PR despite dev review not being completed?

**Review by dipak-demansol — APPROVED** [review]
**LGTM** With the **NOTE** That when i Enable to Todo Plugin then i'm getting error, pls see the attachment. 
image

**Comment by larkox** [comment]
@dipak-demansol I am not able to reproduce this problem in my local. Do you have more specific steps to reproduce?

**Comment by dipak-demansol** [comment]
> @dipak-demansol I am not able to reproduce this problem in my local. Do you have more specific steps to reproduce?

Steps 
1) Upload the binary file of this PR.
2) After Upload Done, Disable Plugin.
3) now enable plugin and you will get the error. pls see the video. 

https://user-images.githubusercontent.com/89907719/153186165-04a97c82-b9d5-4a6e-8fe0-bc9cca71c877.mp4

**Comment by larkox** [comment]
This error should only appear if the plugin is not reachable, that would be when the server is not reachable or the plugin is not enabled. I see you are using a HA configuration, so that might be related, but I still don't understand how or why the plugin is still not enabled when the client calls those endpoints.

Are you able to follow that URL? (you should be able to see the json representation of your todos)

Also, I am seeing something strange in your instance: when you enable the plugin you can see "The plugin is running.plugin is not enabled". Any idea why is that? Maybe something is not working properly in your instance and that is why the error is showing up?

**Comment by dipak-demansol** [comment]
> This error should only appear if the plugin is not reachable, that would be when the server is not reachable or the plugin is not enabled. I see you are using a HA configuration, so that might be related, but I still don't understand how or why the plugin is still not enabled when the client calls those endpoints.
> 
> Are you able to follow that URL? (you should be able to see the json representation of your todos)
> 
> Also, I am seeing something strange in your instance: when you enable the plugin you can see "The plugin is running.plugin is not enabled". Any idea why is that? Maybe something is not working properly in your instance and that is why the error is showing up?

You like to Connect on call to discuss about the issue?

**Comment by larkox** [comment]
After talking with @dipak-demansol it seems that the problem might be related to HA: the plugin gets enabled in one of the nodes faster than the other, so the client fetch from the slower node, which has not yet the plugin enabled.

Is this plausible, @hanzei ? Is this something we want to look a fix for in the short-middle term?

For this plugin in particular, the effect (apart of polluting the console) is minimal, since it would only happen on enable, and this information will be fetched again when a todo is created (or the page is refreshed).

**Comment by hanzei** [comment]
The explanation seems plausible to me.

Could the client be more defensive about fetching data from the plugin e.g. by using a exponential backoff if a 404 is hit?

**Comment by mickmister** [comment]
Does this PR solve the "ask administrator to check the WebSocket port" banner error described here?
https://github.com/mattermost/mattermost-plugin-todo/issues/155#issuecomment-1021397674

@hanzei If this is the case, I'd like to get this merged. Given @DHaussermann's approval to do so, we can cut an RC to deploy to community-daily.

**Comment by hanzei** [comment]
@sanjaydemansol  Could you please give this PR a review ASAP?

**Review by jfrerich — APPROVED** [review]

**Pull request merged**
