### PR TITLE
Bump release 0.6.0 for App Bar

### PR DESCRIPTION
**Pull request by mickmister**
- [x] https://github.com/mattermost/mattermost-plugin-todo/pull/154

https://github.com/mattermost/mattermost-plugin-todo/issues/162

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Comment by hanzei** [comment]
`make apply` needs to be run

**Comment by mickmister** [comment]
@hanzei done

**Review by hanzei — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Review by dipak-demansol — COMMENTED** [review]
Release Testing is Done @DHaussermann please add The review.

**Comment by agarciamontoro** [comment]
@DHaussermann, can we merge this to get the todo plugin native App Bar icon?

**Comment by mickmister** [comment]
@DHaussermann Note that this release only contains the App Bar updates. It has been used many times already in different environments. I'm confident this is ready for merge.

**Review by dipak-demansol — APPROVED** [review]
@mickmister i tested it again on the server where the app-bar-icon was enable and the server where the app-bar-icon was disable and the todo plugin same build worked properly, also tested on the desktop app with those two server and it worked properly so it LGTM.

**Pull request merged**
