### PR TITLE
[MM-21422] bump handlebars from 4.1.2 to 4.5.3

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This ticket bumps the handlebars version

**Steps for bumping**
* git checkout latest master
* git checkout -b bump-handlebars
* make
* cd webapp
* npm install --D handlebars@4.5.3

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21422

### CODE REVIEW

**Comment by jfrerich** [comment]
@jwilander, @crspeller, can one of you please verify the steps I used.  This is the first time bumping a version in one of our repos.  Thanks.

**Comment by crspeller** [comment]
@jfrerich Not sure about that way to do it. Usually if I am doing that manually I do an `npm audit fix`. 
I also kicked off a PR from the security bot to do the upgrade: https://github.com/mattermost/mattermost-plugin-todo/pull/23

**Comment by jfrerich** [comment]
@crspeller I wasn't aware of the `dependabot` usage and am creating a doc for release processes, including dependency bumps.  If the doc exists somewhere, can you point me to it or describe how you kicked off the PR?

**Comment by crspeller** [comment]
@jfrerich Usually dependabot is automatic. You can tell it to try again if it fails the first time in the security tab. But I think you need to be an admin for that.

**Pull request closed without merging**
