### PR TITLE
Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by jfrerich**
### Summary
Bump version to v0.2.0

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* 1052671 [GH-12] Request a task from another user (#27)
* e4dbc40 [GH-7] Include permalink when using the Post-action todo action (#17)
* 51b97cf command - /todo  returns the list of todos (#26)
* 00bac63 [GH-19] Add markdown support to Todos (#20)
* c62d06b Update README.md (#11)

#### Fixes
* 7a97700 Sync with plugin-starter-template (#35)
* da2e33a [GH-28] Delete items when removing them from the order (#29)
* 4670767 Bump handlebars from 4.1.2 to 4.7.1 in /webapp (#23)
* a4ed527 Fix empty task (#18)
* 14e1685 Bump Mattermost to 5.18 (#16)
* 27c14e8 Go 1.13 and fixing the tests (#10)
* dd232e2 Fix auto complete description (#15)
* c1df9e9 Added Help Wanted link to README (#13)

### Ticket Link
https://mattermost.atlassian.net/browse/MM-23177

#### Waiting on the following
- [x] https://github.com/mattermost/mattermost-plugin-todo/pull/39
- [x] https://github.com/mattermost/mattermost-plugin-todo/issues/25
- [x] https://github.com/mattermost/mattermost-plugin-todo/issues/3 - ticket closed
- [x] issue https://github.com/mattermost/mattermost-plugin-todo/issues/48  PR https://github.com/mattermost/mattermost-plugin-todo/pull/49

### CODE REVIEW

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-todo/issues/3 and https://github.com/mattermost/mattermost-plugin-todo/issues/25 are also marked for this release. Should they also be included?

**Comment by jfrerich** [comment]
> #3 and #25 are also marked for this release. Should they also be included?

Issue #3 has not been picked up by anyone.  

Issue #25 was originally picked up by @larkox, but I'm not sure if his schedule permits fixing right now?

What is the time frame we are trying to hit with the releases?

**Comment by larkox** [comment]
I was planning on having a PR for https://github.com/mattermost/mattermost-plugin-todo/issues/25 for today. Not sure how long will it take for the review.

**Comment by jfrerich** [comment]
Reviews will be swift :)

**Comment by larkox** [comment]
Here is the PR for #25 : https://github.com/mattermost/mattermost-plugin-todo/pull/40

**Comment by jfrerich** [comment]
@levb @DHaussermann.  I had to resolve merge master and resolve conflicts that dismissed reviews.  After your 2 approvals, I'll cut the release and file a ticket to marketplace.

**Comment by DHaussermann** [comment]
@jfrerich End to End testing on this found an issue. There seem to be a few cases where the appropriate user no longer receives a DM when the status of an item is changed by another user. 

I tested in master branch as well in case there was just a missing merge to version bump branch. 
I created https://github.com/mattermost/mattermost-plugin-todo/issues/48 to investigate this.
CC @larkox let me know if you have any thoughts to share about this issue.

**Comment by jfrerich** [comment]
@DHaussermann, can you re-review the latest changes that were merged from master?  This includes the fixes for the E2E issue you noted here (https://github.com/mattermost/mattermost-plugin-todo/pull/38#issuecomment-612231254)

**Pull request merged**
