### PR TITLE
Bump to 0.7.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- #176
- #174
- #161
- #180
- #182
- #189

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-todo/issues/178

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Re-tested merged-in fixes
- Completed test cycle
- Added a missing test to cover functionality that acce[ted ToDos can no longer be bumped or deleted
- A few pre-existing minor issues reported
- https://github.com/mattermost/mattermost-plugin-todo/issues/183 which already exists in `v0.6.0` is still unsolved and will beed to be addressed later
- Version correctly set to `v0.7.0`
LGTM!

**Comment by mickmister** [comment]
@DHaussermann I decided to include the ReactDOM changes here, since we haven't released this yet. We are currently running `0.7.0-rc2` on community. I am cutting `0.7.0-rc3` which has the ReactDOM fix.

**Comment by DHaussermann** [comment]
@mickmister I have now retested then release on server versions with the react version upgraded and without. In both cases the plugin is working normally.

I'm not sure if this rc3 is on community yet or if there are other next steps. Please advise.

**Comment by mickmister** [comment]
@DHaussermann If you're good with these changes (based on your comment above I think you are), I'd like to get this merged and deployed to the marketplace

**Pull request merged**
