### PR TITLE
Release bump 0.5.1

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Fixes:

- https://github.com/mattermost/mattermost-plugin-todo/pull/156

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed.
- Tried a few times to reproduce client side JS error on websocket reconnect event. Could not reproduce, Issue appears resolved
- No other PRs were added
- Spot checked other ToDo functionality    
- Version stamp correctly set to `v0.5.1`
No issues found LGTM!

**Comment by DHaussermann** [comment]
@hanzei and @mickmister What are next steps on releasing this. 
This is ready for a release cut once version bump is merged.

Not sure what next steps are on this afterwards, Typically would be ready for marketplace release but there was discussion of promoting to community for soak-time first.
cc @aaronrothschild

**Comment by aaronrothschild** [comment]
Thanks @DHaussermann , I think we should ship it.  We've tested it for the root cause, which I assume we fixed.  There are customers with v5.0 who may not know about this error and more people will come online on Tuesday causing errors on their servers.  I think we are best served by shipping quick, so Admins can upgrade and fix the issue that may be looking on their servers right now.  We should simultaneously ship to community and watch for performance and logging issues. 

cc @hanzei @mickmister @catalintomai

**Comment by catalintomai** [comment]
@DHaussermann , I'll install it on community immediately once we release it to the Marketplace, just lmk. Not clear how to watch for perf/logging issues - are you/QA team aware of any alerts/monitoring systems on community?

**Comment by DHaussermann** [comment]
@catalintomai To this point regarding logs ☝️ I have some access to dashboard for community but unfortunately it is limited to plugin related data which may not serve us for this issue.

I have dropped a link and question in the QA channel to see if there is another resource that may have more access to Community logs so I can follow up.

**Pull request merged**
