### PR TITLE
[GH-232]: Fix e2e playwright directory linting

### PR DESCRIPTION
**Pull request by c0d33ngr**
#### Summary
This pull request fix linting errors in the ```e2e/playwright``` directory.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/232

### CODE REVIEW

**Comment by c0d33ngr** [comment]
I've remove the comments @mickmister 😊

**Comment by mickmister** [comment]
@c0d33ngr Playwright linting is passing now. Nice job :+1:

> Hi @mickmister , I'd love to resolve the golangci-lint error. Should I create a separate PR for it or resolved it in this PR?

Awesome!! I think a separate PR makes sense since this PR currently has no server-side Go changes. LMK if you have any questions about the task. Thanks @c0d33ngr!

**Comment by c0d33ngr** [comment]
It's okay @raghavaggarwal2308 😊

**Comment by mickmister** [comment]
@c0d33ngr Can you please update your local copy of the master branch, and merge its contents into your branch? Thank you!

**Comment by c0d33ngr** [comment]
I've done it @mickmister

**Review by mickmister — APPROVED** [review]
LGTM, thanks @c0d33ngr!

**Pull request merged**
