### PR TITLE
(wip) Go 1.13 and fixing the tests

### PR DESCRIPTION
**Pull request by levb**

### CODE REVIEW

**Comment by levb** [comment]
@jwilander do you mind fixing the npm tests, please?

**Comment by jwilander** [comment]
Can do

**Comment by jwilander** [comment]
I just removed the full screen modal test as it was copied from the web app and it would be non-trivial work to test (besides long term we should be importing that modal not copying code directly)

**Comment by levb** [comment]
@jwilander @jfrerich looks happy now, had to do a few more tweaks to make `eslint` happy.

**Pull request merged**
