### PR TITLE
add plugin info command

### PR DESCRIPTION
**Pull request by svelle**
I wanted to know the version of the plugin on a server I wasn't admin on and realized this plugin have a way to do that.

Added a simple info command to show the installed version.

### CODE REVIEW

**Comment by larkox** [comment]
@aaronrothschild I just wanted your confirmation on this feature. I see no harm in this, and might be useful. The text should be something like:
`Todo plugin version: 1.4.0`

**Comment by larkox** [comment]
@aaronrothschild Any thoughts on this?

**Comment by aaronrothschild** [comment]
For me, when supporting customers - they may not have access to the system console to see the version and API is kinda funky for some users. 

I'd be more inclined to include the version number on the Help screen rather than adding a new command.

**Comment by svelle** [comment]
@aaronrothschild I thought about that as well, I just added it as an additional command because it's like that in some other plugins as well. I can move it to the help screen no problem.

**Pull request closed without merging**
