### PR TITLE
Remove CODEOWNERS

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
I don't actively maintain this plugin anymore, and many things are happening that I am completely detached from, so I guess it is better if I get removed from the codeowners.

That way is more clear when a review from my side is looked for, or just added as a codeowner, and avoid noise or waiting on your side.

#### Ticket Link
NONE

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
Do you also want to remove yourself from the README?

**Comment by larkox** [comment]
@hanzei There is already an open PR for that (https://github.com/mattermost/mattermost-plugin-todo/pull/227). I can do it also here, but 0/5.

**Comment by hanzei** [comment]
1/5 let's do that as part of this PR

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
I don't want community PRs that come in to be missed at everything's current state. Sort of a "dead tarzan" if we simply remove the CODEOWNERS file. @hanzei Thoughts on putting that on me for now?

**Pull request merged**
