### PR TITLE
Fix plugin visuals to handle different themes

### PR DESCRIPTION
**Pull request by colorfusion**
#### Summary

This pull request will adjust the visuals of the plugin, allowing the plugin to adapt to different themes in the application accordingly.  
The style has been adjusted slightly to differentiate the different components in the plugin, and to follow Mattermost's layout more closely.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/78

##### Sidebar
image 
image

##### Add / Request Todo (root page)
image image
image image

#### Todo Message Input
image
image

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Awesome job, @colorfusion ! Thank you very much.

LGMT

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
@colorfusion We only use theme variables in the multiples of 4.

**Comment by asaadmahmood** [comment]
> @colorfusion We only use theme variables in the multiples of 4.

You can see the variables available in the utils file of the webapp:
https://github.com/mattermost/mattermost-webapp/blob/master/utils/utils.jsx
Screenshot 2020-08-27 at 1 12 08 PM

**Comment by colorfusion** [comment]
I've adjusted the theme variables to be in multiple of 4, and fixed the input box's border with new screenshots in the PR.
Do let me know if there are any additional changes that should be made as well.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by asaadmahmood — APPROVED** [review]

**Review by larkox — APPROVED** [review]
LGTM!

**Pull request merged**
