### PR TITLE
Add Homepage and Support URL

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Tested locally and the link shows up in the Marketplace

#### Ticket Link
https://community-release.mattermost.com/core/pl/mgrez65gjfngbbjqqho9ka1xte

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann This might be a good candidate for dev testing as the change is quite small.

**Comment by DHaussermann** [comment]
Agreed @hanzei this is well suited.
@larkox or @jfrerich, If you have a bit of time, could one of you peer-test this PR using the  peer testing process documented here: https://mattermost.atlassian.net/wiki/spaces/INT/pages/619937892/Peer+Testing+Process (Any feedback on how we can clarify the process is appreciated.)

**Comment by larkox** [comment]
@DHaussermann I will do it :D

**Comment by larkox** [comment]
@DHaussermann Peer testing finished.
Scope:
Add plugin homepage so it is reachable from the plugin Marketplace.

Testing:
When installed in local server and disabled the remote marketplace, the name of the plugin is a link to the github page of the todo plugin.
Clicking on the name of the plugin, opens a new window with the github page of the todo plugin.

Follow-up concerns:
Support URL also set, but it is yet not used anywhere in the marketplace.

**Pull request merged**
